name: CI ReUse Dev
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  NodeJS_Build:
    if: inputs.appType == 'nodejs'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: npm install
        name: Download Dependencies
  Maven_Build:
    if: inputs.appType == 'maven'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: mvn package
  Angular_Build:
    if: inputs.appType == 'angular'
    runs-on: self-hosted
    steps:
      - run: echo ng build



