name: CI ReUse Main
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
    secrets:
      vault_token:
        required: true
jobs:
  Build:
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      docker_build: "false"
    secrets:
      vault_token: ${{ secrets.vault_token }}
  Test:
    needs: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo npm install
          echo npm test
        name: Run NodeJS Tests
        if: inputs.appType == 'nodejs'
      - run: echo mvn test
        name: Run Maven Tests
        if: inputs.appType == 'maven'
      - run: echo python -m unittest
        name: Run Python Tests
        if: inputs.appType == 'python'
  DockerBuild:
    needs: Test
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      docker_build: "true"
    secrets:
      vault_token: ${{ secrets.vault_token }}

  Dev_deploy:
    needs: DockerBuild
    environment: DEV
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/aks-deploy.yml@main
    with:
      appEnv: 'dev'
      resourceGroup: 'ukwest-dev'
    secrets:
      vault_token: ${{ secrets.vault_token }}

  Qa_Deploy:
    environment: QA
    runs-on: self-hosted
    needs: Dev_deploy
    steps:
      - run: echo OK
  Uat_Deploy:
    environment: UAT
    runs-on: self-hosted
    needs: Qa_deploy
    steps:
      - run: echo OK
  Prod_Deploy:
    environment: PROD
    runs-on: self-hosted
    needs: Uat_Deploy
    steps:
      - run: echo OK




