name: CI ReUse Main
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  Build:
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
  Test:
    needs: Build
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/test.yml@main
    with:
      appType: '${{ inputs.appType }}'
  DockerBuild:
    runs-on: self-hosted
    needs: Test
    steps:
      - uses: raghudevopsb84/roboshop-github-actions/.github/workflows/build.yml@main
        with:
          appType: '${{ inputs.appType }}'
      - run: docker build .
        name: Docker Build
  Dev_deploy:
    environment: DEV
    runs-on: self-hosted
    needs: DockerBuild
    steps:
      - run: echo OK
  Qa_Deploy:
    environment: QA
    runs-on: self-hosted
    needs: Dev_deploy
    steps:
      - run: echo OK
  Uat_Deploy:
    environment: UAT
    runs-on: self-hosted
    needs: Qa_deploy
    steps:
      - run: echo OK
  Prod_Deploy:
    environment: PROD
    runs-on: self-hosted
    needs: Uat_Deploy
    steps:
      - run: echo OK




