name: CI ReUse Main
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
    secrets:
      vault_token:
        required: true
jobs:
  Build:
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      docker_build: "false"
    secrets:
      vault_token: ${{ secrets.vault_token }}
  Test:
    needs: Build
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/test.yml@main
    with:
      appType: '${{ inputs.appType }}'
  DockerBuild:
    needs: Test
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      docker_build: "true"
    secrets:
      vault_token: ${{ secrets.vault_token }}
  Dev_deploy:
    environment: DEV
    runs-on: self-hosted
    needs: DockerBuild
    steps:
      - run: echo OK
  Qa_Deploy:
    environment: QA
    runs-on: self-hosted
    needs: Dev_deploy
    steps:
      - run: echo OK
  Uat_Deploy:
    environment: UAT
    runs-on: self-hosted
    needs: Qa_deploy
    steps:
      - run: echo OK
  Prod_Deploy:
    environment: PROD
    runs-on: self-hosted
    needs: Uat_Deploy
    steps:
      - run: echo OK




