name: Github Runner Docker Image
on:
  workflow_dispatch:
  push:
    paths:
      - 'runner-docker-image/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: |
          docker build -t rkalluru/d84-github-runner .


